// Opt-in hardware test. Fixture is a synthetic MP3 generated by ffmpeg, not user media.
const {Engine}=require('../apps/nodivu-electron/engine.cjs');
const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const engine=new Engine(path.join(root,'target/release/nodivu-app-backend.exe'),{...process.env,NODIVU_SCAN_PLUGINS:'1',NODIVU_PLUGIN_MANIFEST:path.join(root,'.local/plugins/plugin.json')});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const catalog=await engine.request('plugins.list');assert.ok(catalog.plugins.some(p=>p.id==='org.nodivu.mp3-player'&&p.source&&p.file_player));
 let s=await engine.request('session.snapshot');
 async function add(kind,plugin_id){s=await engine.request('node.add',{expected_revision:s.revision,kind,...(plugin_id?{plugin_id}:{})});return s.graph.nodes.at(-1).id;}
 const player=await add('plugin','org.nodivu.mp3-player'),gain=await add('gain'),output=await add('output');
 const devices=(await engine.request('devices.list')).devices;
 const endpoint=devices.find(d=>d.flow==='render'&&d.state==='active'&&d.is_default);assert.ok(endpoint);
 const graph=structuredClone(s.graph);graph.nodes.find(n=>n.id===output).block.endpoint_id=endpoint.endpoint_id;graph.nodes.find(n=>n.id===gain).block.gain_db=-12;
 graph.edges=[{from:player,to:gain},{from:gain,to:output}];s=await engine.request('graph.apply',{expected_revision:s.revision,graph});
 await wait(250);
 await engine.request('plugin.command',{node_id:player,action:'load',path:path.join(root,'.local/mp3-test.mp3')});
 async function until(predicate){for(let i=0;i<100;i++){await wait(80);s=await engine.request('session.snapshot');assert.ok(s.plugin_states[player].status>=0,JSON.stringify(s.plugin_states));if(predicate(s))return;}throw new Error('Prazo excedido: '+JSON.stringify(s.plugin_states));}
 await until(s=>s.plugin_states[player].status===2);assert.equal(s.metrics.output_peak,0);
 const generation=s.generation;
 for(let i=0;i<2;i++){
  await engine.request('plugin.command',{node_id:player,action:'play'});
  await until(s=>s.metrics.output_peak>0.0001);assert.equal(s.signal,3);assert.equal(s.generation,generation);
  await until(s=>s.plugin_states[player].status===4&&s.metrics.output_peak===0);assert.equal(s.metrics.processor_errors,0);
 }
 fs.writeFileSync(path.join(root,'.local/mp3-evidence.json'),JSON.stringify({catalog,endpoint,snapshot:s},null,2));
 console.log('PASS: MP3 -> ganho -> WASAPI, fim em silêncio, Play duas vezes sem reabrir, catálogo com ganho e player.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>engine.stop());
